name: rdp-windows

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 525600

    steps:
    - name: Téléchargement de Ngrok & de NSSM
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/Kaysuto/rdp-windows/blob/main/Fichiers/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32        
    - name: Extraction de Ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Téléchargement des fichiers importants.
      run: |
        Invoke-WebRequest https://github.com/Kaysuto/rdp-windows/blob/main/Fichiers/NGROK-EU.bat -OutFile NGROK-EU.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Kaysuto/rdp-windows/main/Fichiers/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Kaysuto/rdp-windows/main/Fichiers/loop.bat -OutFile loop.bat
    - name: Création d'un fichier YML pour NGROK.
      run: start NGROK-EU.bat
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Création d'un tunnel
      run: .\ngrok\ngrok.exe tcp 3389
    - name: Connexion à votre RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: Tout est prêt ! Vous pouvez fermer l'onglet maintenant ! Durée maximale de la VM - 1 ans.
      run: cmd /c loop.bat
